theme: minima
title: Welcome to this page!
author: Sheloyni
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I'm trying to learn the github page now


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
